api-version: v1
management:
  endpoint:
    health:
      group:
        readiness:
          include: '*'
          show-details: always
        liveness:
          show-details: never
          include: ping

server:
  port: 7759
  #  verify-endpoint: https://localhost:7759/verify?token=
  endpoint: http://localhost:7759
  reminder-path: /reminder/update
  revert-path: /revert
  verify-path: /verify

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/todo
    username: root
    password: paddleW98

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted

aws:
  dynamo-db:
    ttl: 600
    table-name: 'test-dev-csye7125'
  sns:
    topic-name: 'arn:aws:sns:us-east-1:963552526238:test-dev-csye7125'
    from: 'notify@o2hkk.ninja'
  s3:
    bucket-name: 'prod.lambda.stk'
    localpath:
      default: "D:/Attachments/"

limit:
  attachment:
    amount: 5
  tag:
    amount: 10
  reminder:
    amount: 5
