api-version: v1
management:
  endpoint:
    health:
      group:
        readiness:
          include: '*'
          show-details: always
        liveness:
          show-details: never
          include: ping

server:
  port: 7759
#  verify-endpoint: https://localhost:7759/verify?token=
  endpoint: http://localhost:7759

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: ra9ra9

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted

aws:
  dynamo-db:
    ttl: 600
    table-name: 'test-prod-csye7125'
  sns:
    topic-name: 'arn:aws:sns:us-east-1:039848784614:test-prod-csye7125'
    from: 'notify@prod.aws.ethanzhang1997.me'
  s3:
    bucket-name: 'prod.lambda'
    localpath:
      default: "D:/Attachments/"

limit:
  attachment:
    amount: 5
  tag:
    amount: 10
  reminder:
    amount: 5
